repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
  # Make docstrings PEP 257 compliant
  - repo: https://github.com/PyCQA/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
        # disable wrap-summaries to avoid the headache of rewording many docstrings.
        args: ["--in-place", "--black", "--wrap-summaries=0"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.6
    hooks:
      - id: clang-format
        #  - repo: https://github.com/markdownlint/markdownlint
        #    rev: v0.13.0
        #    hooks:
        #      - id: markdownlint
  - repo: local
    hooks:
      - id: signed-off-by
        name: Developer Certificate of Origin
        language: pygrep
        entry: 'Signed-off-by:'
        args: [--negate]
        stages: [commit-msg]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
